pipeline {
    agent any
    environment {
        dockerhub=credentials('docker')
    }

    stages {
        stage('code status') {
            steps {
                sh 'echo code successfully pulled'
            }
        }
        stage('Building the docker image') {
            steps {
                sh 'cd webapp && docker build -t muralialakuntla3/webapp .'
            }
        }
         stage('Running the docker container') {
            steps {
                 // sh 'docker container rm --force webapp1'
                  sh 'docker container run -dt -p 80:80 --name webapp1 muralialakuntla3/webapp'
            }
        }

    }
}
